version: '3'

volumes:
  db-data: 
  mongo-data:
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
      args:
        MONGO_URI: $MONGO_URI
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/api
    depends_on:
      - mongo
    links:
      - mongo
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    environment:
      -  'MONGODB_USER=root'
      -  'MONGODB_PASS=password'
    ports:
        - "27017:27017"
    volumes:
        - "mongo-data:/data/db"

  mongo-express:
    container_name: mongo-express
    links:
      - 'mongo:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=root'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password'
    image: mongo-express
  
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api/:/api
      - /etc/letsencrypt:/etc/letsencrypt
    command: /bin/sh -c "envsubst '$$NGINX_SERVER_NAME'< /etc/nginx/conf.d/api.conf.template > /etc/nginx/conf.d/defapapiiault.conf && nginx -g 'daemon off;'"
    environment:
      NGINX_SERVER_NAME: $NGINX_SERVER_NAME

  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/drill-app-api/api/public:/var/www/drill-app-api/api/public
    command: ["--version"]
