version: '3'

volumes:
  db-data: 
  mongo-data:
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api/:/api
    depends_on:
      - mongo
    links:
      - mongo
    stdin_open: true
    tty: true
    restart: always

  mongo:
    image: mongo:latest
    environment:
      -  'MONGODB_USER=root'
      -  'MONGODB_PASS=password'
    ports:
        - "27017:27017"
    volumes:
        - "mongo-data:/data/db"
    restart: always

  mongo-express:
    container_name: mongo-express
    links:
      - 'mongo:mongo'
    ports:
      - '8081:8081'
    environment:
      - 'ME_CONFIG_OPTIONS_EDITORTHEME=ambiance'
      - 'ME_CONFIG_BASICAUTH_USERNAME=root'
      - 'ME_CONFIG_BASICAUTH_PASSWORD=password'
    image: mongo-express
  
  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./api/:/api
    restart: always


